# GitLab CI/CD Pipeline for Deploy to Server
stages:
  - test
  - deploy

# test:
#   script:
#     - flake 8 .

.deploy_template: &deploy_template
  image: alpine:latest
  script:
      ssh "$SSH_USER@$SSH_HOST" <<EOF
      become $TOOLNAME
      webservice python3.11 start\
      source $HOME/www/python/venv/bin/activate
      pip install -r $HOME/www/python/src/requirements.txt
      exit
      webservice python3.11 restart
      EOF

deploy-test:
  stage: deploy
  variables:
    environment: test
    SSH_HOST: "login.tools.wmflabs.org"
    SSH_USER: "eugene233"
    TOOLNAME: $TOOLNAME
    BRANCH: main
    ACCESS_TOKEN: $TOOL_ACCESS_TOKEN
    SECURE_FILES_DOWNLOAD_PATH: .
    PRIVATE_KEY_NAME: "id_rsa"
  
  <<: *deploy_template