# GitLabCI/CD Pipeline for Deploy to Server
stages:
  - test
  - deploy


# test:
#   script:
#     - flake 8 .

.deploy_template: &deploy_template
  image: alpine:latest
  script:
    - apk add --no-cache curl openssh-client git bash
    - mkdir -p ~/.ssh
    - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
    - echo "$TF_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - ls -l ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - git config --global user.email "gitlab-ci@$CI_SERVER_HOST"
    - git config --global user.name "GitLab CI"
    - git checkout -b $BRANCH || git checkout $BRANCH
    - echo "Pushing to branch $BRANCH"
    - git init -b $BRANCH
    - git remote add gitlab_origin https://GITLAB_ACCESS_TOKEN:$ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
    - git add .
    - git commit -m "Build from commit $CI_COMMIT_SHA - $CI_COMMIT_MESSAGE" || echo "No changes to commit"
    - git log -1
    - git status
    - echo "Restart service on Toolforge"
    - |
      ssh -vtt -i "~/.ssh/id_ed25519" "$SSH_USER@$SSH_HOST" <<EOF
      become $TOOLNAME
      webservice python3.11 start
      source $HOME/www/python/venv/bin/activate
      pip install -r $HOME/www/python/src/requirements.txt
      exit
      webservice python3.11 restart
      EOF

deploy-test:
  stage: deploy
  variables:
    environment: test
    SSH_HOST: "login.tools.wmflabs.org"
    SSH_USER: "eugene233"
    TOOLNAME: $TOOLNAME
    BRANCH: main
    ACCESS_TOKEN: $TOOL_ACCESS_TOKEN

  
  <<: *deploy_template