# GitLabCI/CD Pipeline for Deploy to Server

stages:
  # - build
  - deploy

# build:
#   # This stage installs dependencies, builds the application, and prepares it for deployment.
#   stage: build
#   image: node:22
#   tags:
#     - wmcs
#   cache:
#     key:
#       files:
#         - package-lock.json
#     paths:
#       - node_modules/
    
#   script:
#     - npm --version
#     - mkdir -p ~/.ssh
#     - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
#     - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
#     - mv $SECURE_FILES_DOWNLOAD_PATH/$PRIVATE_KEY_NAME ~/.ssh
#     - chmod 600 ~/.ssh/$PRIVATE_KEY_NAME
#     - |
#       ssh -vtt -i "~/.ssh/id_rsa" "$SSH_USER@$SSH_HOST" <<EOF
#       become $TOOLNAME
#       cd /www/python/src
#       npm install
#       npm run build
#       exit

  # artifacts:
  #   paths:
  #     - /www/python/src/isa/static/js/
  #   expire_in: 1 day

#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

.deploy_template: &deploy_template
  # Using node:22-alpine because the script needs git and ssh for deployment
  image: node:22-alpine
  script:
    - apk update
    - apk add --no-cache curl openssh-client git bash # No need to install nodejs npm since the image already has it
    - npm --version
    - mkdir -p ~/.ssh
    - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - mv $SECURE_FILES_DOWNLOAD_PATH/$PRIVATE_KEY_NAME ~/.ssh
    - chmod 600 ~/.ssh/$PRIVATE_KEY_NAME
    - git config --global user.email "gitlab-ci@$CI_SERVER_HOST"
    - git config --global user.name "GitLab CI"
    - git checkout -b $BRANCH || git checkout $BRANCH
    - echo "Pushing to branch $BRANCH"
    - git init -b $BRANCH
    - git remote add gitlab_origin https://GITLAB_ACCESS_TOKEN:$ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
    - git add .
    - git commit -m "Build from commit $CI_COMMIT_SHA - $CI_COMMIT_MESSAGE" || echo "No changes to commit"
    - git log -1
    - git status
    - echo "Restart service on Toolforge"
    - |
      ssh -i "~/.ssh/id_rsa" "$SSH_USER@$SSH_HOST" <<EOF
      become $TOOLNAME
      webservice python3.13 stop
      cd www/python/src
      git pull origin main
      cd
      exit
      webservice python3.13 start
      exit
      EOF

#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

deploy-test:
  stage: deploy
  variables:
    environment: test
    SSH_HOST: "login.tools.wmflabs.org"
    SSH_USER: "eugene233"
    TOOLNAME: $TOOLNAME
    BRANCH: main
    ACCESS_TOKEN: $TOOL_ACCESS_TOKEN
    SECURE_FILES_DOWNLOAD_PATH: .
    PRIVATE_KEY_NAME: "id_rsa"
  
  <<: *deploy_template